apiVersion: v1
kind: Service
metadata:
  name: fog-node-red-service
spec:
  selector:
    app: fog-node-red
  ports:
    - protocol: UDP
      name: coap
      port: 5683
      targetPort: 5683
      nodePort: 30000
    - protocol: TCP
      name: http
      port: 1880
      targetPort: 1880
      nodePort: 30001
  type: NodePort