---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  MONGO_URI: "mongodb://s222177103:OPkr3ZdpGQRu0JFf@cloud-mongodb-service.default.svc.cluster.local:27017/sit314?retryWrites=true&w=majority&authSource=admin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-manager
  template:
    metadata:
      labels:
        app: delivery-manager
    spec:
      containers:
        - name: delivery-manager
          image: docker.io/sicsix/delivery-manager
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: SCHEDULE_MANAGER_URI
              value: "http://schedule-manager-service.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: docker.io/sicsix/order-manager
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: DELIVERY_MANAGER_URI
              value: "http://delivery-manager-service.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-manager
  template:
    metadata:
      labels:
        app: sales-manager
    spec:
      containers:
        - name: sales-manager
          image: docker.io/sicsix/sales-manager
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: SHELF_MANAGER_URI
              value: "http://shelf-manager-service.default.svc.cluster.local"
            - name: STOCK_MANAGER_URI
              value: "http://stock-manager-service.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedule-manager
  template:
    metadata:
      labels:
        app: schedule-manager
    spec:
      containers:
        - name: schedule-manager
          image: docker.io/sicsix/schedule-manager
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: SHELF_MANAGER_URI
              value: "http://shelf-manager-service.default.svc.cluster.local"
            - name: STOCK_MANAGER_URI
              value: "http://stock-manager-service.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelf-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shelf-manager
  template:
    metadata:
      labels:
        app: shelf-manager
    spec:
      containers:
        - name: shelf-manager
          image: docker.io/sicsix/shelf-manager
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: SCHEDULE_MANAGER_URI
              value: "http://schedule-manager-service.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-manager
  template:
    metadata:
      labels:
        app: stock-manager
    spec:
      containers:
        - name: stock-manager
          image: docker.io/sicsix/stock-manager
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_URI
            - name: PORT
              value: "80"
            - name: ORDER_MANAGER_URI
              value: "http://order-manager-service.default.svc.cluster.local"